name: markdown
version: 0.3.6
author: Dart Team <misc@dartlang.org>
description: A library for converting markdown to HTML.
homepage: https://github.com/dpeek/dart-markdown
dependencies:
  html5lib: any
  unittest: any
  analyzer_experimental: any
